name: Build Docker and push to docker hub

on:
  push:
    branches: [ main ]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout Repo
           uses: actions/checkout@v2

         - name: Build Image
           run: docker build -t demo_app_2 .

         - name: Login
           uses: docker/login-action@v1
           with: 
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

         - name: Push
           run: docker push demo_app_2
         
