name: Lab Dashboard CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Chicken Farm MS Version 2
      uses: actions/checkout@v1
    
    - name: Deploy Chicken Farm MS
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PORT: ${{ secrets.SSH_PORT }}
        PASSWORD: ${{ secrets.SSH_PASSWORD }}
        source: "."
        target: "/var/www/html/projects_demo/lab_dashboard"
